### PR TITLE
Describe how-to obtain Java Native Binary

### PR DESCRIPTION
**Pull request by abelsromero**
#1

### CODE REVIEW

**Comment by ebarlas** [comment]
Thank you for this, @abelsromero!

However, I'm more interested in the _underlying_ GraalVM commands without the use of Gradle. Are you familiar with those?

**Comment by abelsromero** [comment]
It can be done, but I really don't recommend that. It still requires compiling and generating the jar and configuring classpath, all by hand.
I find this case interesting because if the goal of this experiment is obtaining a small package, this is the best approach imho, but is fine if you don't consider this a goal.

**Comment by ebarlas** [comment]
Hi @abelsromero, I included a new GraalVM section in the docs with benchmark results. Thank you for suggesting the inclusion of GraalVM. The results are impressive!

https://github.com/ebarlas/java-httpserver-vthreads/commit/a801b71f9bd689beb4ad9f0ebadab542aa583c5e

**Comment by ebarlas** [comment]
Closing this PR since GraalVM native-image details were added to the README.

**Pull request closed without merging**
